name: Publish to NPM

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Publish to NPM
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *"-beta"* ]]; then
            echo "Detected beta version: $VERSION - Publishing with tag 'beta'"
            npm publish --access public --tag beta
          else
            echo "Detected production version: $VERSION - Publishing to 'latest'"
            npm publish --access public
          fi
